# Generated by Django 5.1.7 on 2025-03-26 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DepartmentCode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('StaffNumber', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('SemesterCode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SemesterName', models.CharField(max_length=50)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentNumber', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogs',
            fields=[
                ('LogId', models.AutoField(primary_key=True, serialize=False)),
                ('AdminName', models.CharField(max_length=50)),
                ('LogDescription', models.CharField(max_length=100)),
                ('DateAndTime', models.DateTimeField(auto_now_add=True)),
                ('Details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('AssessmentCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('AssessmentName', models.CharField(max_length=100)),
                ('TotalMark', models.IntegerField()),
                ('StaffNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecognition',
            fields=[
                ('FaceRecognitionId', models.AutoField(primary_key=True, serialize=False)),
                ('FaceImg', models.BinaryField()),
                ('StudentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('StudentMarkId', models.AutoField(primary_key=True, serialize=False)),
                ('MarksObtained', models.IntegerField()),
                ('AssessmentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.assessment')),
                ('StudentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('SubjectCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=100)),
                ('DepartmentCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.department')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('StudentProgressId', models.AutoField(primary_key=True, serialize=False)),
                ('Grade', models.CharField(max_length=10)),
                ('StudentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.student')),
                ('SubjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LecturerCourses',
            fields=[
                ('LecturerCourseId', models.AutoField(primary_key=True, serialize=False)),
                ('StaffNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.lecturer')),
                ('SubjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('EnrollmentId', models.AutoField(primary_key=True, serialize=False)),
                ('SemesterCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.semester')),
                ('StudentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.student')),
                ('SubjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('AttendId', models.AutoField(primary_key=True, serialize=False)),
                ('DateAndTime', models.DateTimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=10)),
                ('StudentNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.student')),
                ('SubjectCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.subject')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='SubjectCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edutrackApp.subject'),
        ),
    ]
