# Generated by Django 5.1.6 on 2025-04-12 23:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edutrackApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contactNumber',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
